volumes:
  mb-mongo-data:

networks:
  media-browser:
    driver: bridge

services:

  mongo:
    image: mongo:4.4.18
    restart: unless-stopped
    networks:
      - media-browser
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mb-mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - media-browser
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo/"
      ME_CONFIG_BASICAUTH: false

  backend:
    image: bdaviddvlp/media-browser:backend
    container_name: backend
    restart: unless-stopped
    networks:
      - media-browser
    depends_on:
      - mongo
    ports:
      - "3030:3030"
    environment:
      LOG_LEVEL: 'info'
      MONGO_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo/${MONGO_INITDB_DATABASE}?authSource=admin"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3030
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    volumes:
      - ./backend/config/local.json:/app/config/local.json

  frontend:
    image: bdaviddvlp/media-browser:frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - media-browser
    volumes:
      - ./frontend/config/local.json:/app/src/config/local.json
    tty: true
    depends_on:
      - backend
