#!/bin/bash

# Create app directory
mkdir -p "$HOME/.local/share/media-browser"

# Download installer script
curl -s -o "$HOME/.local/share/media-browser/install" https://raw.githubusercontent.com/bdaviddvlp/media-browser-configs/refs/heads/main/init

# Make installer script executable
chmod +x "$HOME/.local/share/media-browser/install"

echo "Installation script downloaded to $HOME/.local/share/media-browser/install"
echo "Run the script with: $HOME/.local/share/media-browser/install"
